name: First Interaction

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey @${{ github.actor }} 👋,\nThank you for raising an issue. Please make sure that it is detailed and clear.'
        pr-message: 'Hey @${{ github.actor }} 👋,\nThank you for submitting a Pull Request. Make sure you have followed all the contribution guidelines.'
